In [1]:
from PIL import Image

In [2]:
image = Image.open('original.png')

In [3]:
from numpy import asarray

In [4]:
data = asarray(image)

In [5]:
print(data)

[[[106 148 189 255]
  [106 148 189 255]
  [106 148 189 255]
  ...
  [ 71 125 169 255]
  [ 71 125 169 255]
  [ 71 125 169 255]]

 [[106 148 189 255]
  [106 148 189 255]
  [106 148 189 255]
  ...
  [ 71 125 169 255]
  [ 71 125 169 255]
  [ 71 125 169 255]]

 [[106 148 189 255]
  [106 148 189 255]
  [106 148 189 255]
  ...
  [ 71 125 169 255]
  [ 71 125 169 255]
  [ 71 125 169 255]]

 ...

 [[102  82  76 255]
  [105  85  78 255]
  [105  85  78 255]
  ...
  [109  89  87 255]
  [112  91  89 255]
  [112  91  89 255]]

 [[104  84  77 255]
  [102  82  76 255]
  [102  82  76 255]
  ...
  [104  83  81 255]
  [104  83  81 255]
  [106  85  83 255]]

 [[106  86  79 255]
  [104  84  77 255]
  [104  84  77 255]
  ...
  [ 87  67  65 255]
  [ 85  64  62 255]
  [ 86  66  64 255]]]


# Converting an Image to Array using Keras:

In [6]:
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
img = load_img("original.png")
data = img_to_array(img)
print(data)

Using TensorFlow backend.


[[[106. 148. 189.]
  [106. 148. 189.]
  [106. 148. 189.]
  ...
  [ 71. 125. 169.]
  [ 71. 125. 169.]
  [ 71. 125. 169.]]

 [[106. 148. 189.]
  [106. 148. 189.]
  [106. 148. 189.]
  ...
  [ 71. 125. 169.]
  [ 71. 125. 169.]
  [ 71. 125. 169.]]

 [[106. 148. 189.]
  [106. 148. 189.]
  [106. 148. 189.]
  ...
  [ 71. 125. 169.]
  [ 71. 125. 169.]
  [ 71. 125. 169.]]

 ...

 [[102.  82.  76.]
  [105.  85.  78.]
  [105.  85.  78.]
  ...
  [109.  89.  87.]
  [112.  91.  89.]
  [112.  91.  89.]]

 [[104.  84.  77.]
  [102.  82.  76.]
  [102.  82.  76.]
  ...
  [104.  83.  81.]
  [104.  83.  81.]
  [106.  85.  83.]]

 [[106.  86.  79.]
  [104.  84.  77.]
  [104.  84.  77.]
  ...
  [ 87.  67.  65.]
  [ 85.  64.  62.]
  [ 86.  66.  64.]]]
